In [1]:
year = None
month = None
program = "default"
study_type = "study"
include_test_users = False
# labels = {}
labels = {'MODE': [{'value': 'walk', 'base_mode': 'WALKING'}, {'value': 'e-bike', 'base_mode': 'E_BIKE'}, {'value': 'bike', 'base_mode': 'BICYCLING'}, {'value': 'bikeshare', 'base_mode': 'BICYCLING'}, {'value': 'scootershare', 'base_mode': 'E_SCOOTER'}, {'value': 'drove_alone', 'base_mode': 'CAR', 'passengers': 1}, {'value': 'shared_ride', 'base_mode': 'CAR', 'passengers': 2}, {'value': 'hybrid_drove_alone', 'base_mode': 'PHEV_CAR', 'passengers': 1}, {'value': 'hybrid_shared_ride', 'base_mode': 'PHEV_CAR', 'passengers': 2}, {'value': 'e_car_drove_alone', 'base_mode': 'E_CAR', 'passengers': 1}, {'value': 'e_car_shared_ride', 'base_mode': 'E_CAR', 'passengers': 2}, {'value': 'taxi', 'base_mode': 'TAXI'}, {'value': 'bus', 'base_mode': 'BUS'}, {'value': 'train', 'base_mode': 'TRAIN'}, {'value': 'free_shuttle', 'base_mode': 'BUS'}, {'value': 'air', 'base_mode': 'AIR'}, {'value': 'not_a_trip', 'base_mode': 'UNKNOWN'}, {'value': 'other', 'base_mode': 'OTHER'}], 'PURPOSE': [{'value': 'home'}, {'value': 'work'}, {'value': 'at_work'}, {'value': 'school'}, {'value': 'transit_transfer'}, {'value': 'shopping'}, {'value': 'meal'}, {'value': 'pick_drop_person'}, {'value': 'pick_drop_item'}, {'value': 'personal_med'}, {'value': 'access_recreation'}, {'value': 'exercise'}, {'value': 'entertainment'}, {'value': 'religious'}, {'value': 'other'}], 'REPLACED_MODE': [{'value': 'no_travel'}, {'value': 'walk'}, {'value': 'bike'}, {'value': 'bikeshare'}, {'value': 'scootershare'}, {'value': 'drove_alone'}, {'value': 'shared_ride'}, {'value': 'hybrid_drove_alone'}, {'value': 'hybrid_shared_ride'}, {'value': 'e_car_drove_alone'}, {'value': 'e_car_shared_ride'}, {'value': 'taxi'}, {'value': 'bus'}, {'value': 'train'}, {'value': 'free_shuttle'}, {'value': 'other'}], 'translations': {'en': {'walk': 'Walk', 'e-bike': 'E-bike', 'bike': 'Regular Bike', 'bikeshare': 'Bikeshare', 'scootershare': 'Scooter share', 'drove_alone': 'Gas Car Drove Alone', 'shared_ride': 'Gas Car Shared Ride', 'hybrid_drove_alone': 'Hybrid Drove Alone', 'hybrid_shared_ride': 'Hybrid Shared Ride', 'e_car_drove_alone': 'E-Car Drove Alone', 'e_car_shared_ride': 'E-Car Shared Ride', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Bus', 'train': 'Train', 'free_shuttle': 'Free Shuttle', 'air': 'Air', 'not_a_trip': 'Not a trip', 'no_travel': 'No travel', 'home': 'Home', 'work': 'To Work', 'at_work': 'At Work', 'school': 'School', 'transit_transfer': 'Transit transfer', 'shopping': 'Shopping', 'meal': 'Meal', 'pick_drop_person': 'Pick-up / Drop off Person', 'pick_drop_item': 'Pick-up / Drop off Item', 'personal_med': 'Personal / Medical', 'access_recreation': 'Access Recreation', 'exercise': 'Recreation / Exercise', 'entertainment': 'Entertainment / Social', 'religious': 'Religious', 'other': 'Other'}, 'es': {'walk': 'Caminando', 'e-bike': 'e-bicicleta', 'bike': 'Bicicleta', 'bikeshare': 'Bicicleta compartida', 'scootershare': 'Motoneta compartida', 'drove_alone': 'Coche de Gas, Condujo solo', 'shared_ride': 'Coche de Gas, Condujo con otros', 'hybrid_drove_alone': 'Coche Híbrido, Condujo solo', 'hybrid_shared_ride': 'Coche Híbrido, Condujo con otros', 'e_car_drove_alone': 'e-coche, Condujo solo', 'e_car_shared_ride': 'e-coche, Condujo con otros', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Autobús', 'train': 'Tren', 'free_shuttle': 'Colectivo gratuito', 'air': 'Avión', 'not_a_trip': 'No es un viaje', 'no_travel': 'No viajar', 'home': 'Casa', 'work': 'Trabajo', 'at_work': 'En el trabajo', 'school': 'Escuela', 'transit_transfer': 'Transbordo', 'shopping': 'Compras', 'meal': 'Comida', 'pick_drop_person': 'Recoger / Entregar Individuo', 'pick_drop_item': 'Recoger / Entregar Objeto', 'personal_med': 'Personal / Médico', 'access_recreation': 'Acceder a Recreación', 'exercise': 'Recreación / Ejercicio', 'entertainment': 'Entretenimiento / Social', 'religious': 'Religioso', 'other': 'Otros'}, 'lo': {'walk': 'ດ້ວຍການຍ່າງ', 'e-bike': 'ວຍລົດຈັກໄຟຟ້າ', 'bike': 'ລົດຖີບ', 'bikeshare': 'ດ້ວຍລົດຖີບທີ່ໃຫ້ເຊົ່າ', 'scootershare': 'ດ້ວຍລົດຈັກສະກູດເຕີ້ໃຫ້ເຊົ່າ ', 'drove_alone': 'ເດີນທາງ ດ້ວຍລົດໃຫ່ຍ ເຊີ່ງເປັນລົດທີ່ຂັບເອງ', 'shared_ride': 'ເດີນທາງດ້ວຍລົດໃຫ່ຍ ຮ່ວມກັບລົດຄົນອຶ່ນ', 'hybrid_drove_alone': 'ລົດປະສົມຂັບຄົນດຽວ', 'hybrid_shared_ride': 'ລົດປະສົມທີ່ໃຊ້ຮ່ວມກັນ', 'e_car_drove_alone': 'ດ້ວຍການຂັບລົດໄຟຟ້າໄປເອງ', 'e_car_shared_ride': 'ດ້ວຍການຈ້າງລົດໄຟຟ້າໄປ', 'taxi': 'ແທັກຊີ', 'bus': 'ລົດເມ', 'train': 'ລົດໄຟ', 'free_shuttle': 'ລົດຮັບສົ່ງຟຣີ', 'air': 'ຍົນ', 'not_a_trip': 'ບໍ່ແມ່ນການເດີນທາງ', 'no_travel': 'ບໍ່ມີການເດີນທາງ', 'home': 'ບ້ານ', 'work': 'ໄປເຮັດວຽກ', 'at_work': 'ຢູ່ບ່ອນເຮັດວຽກ', 'school': 'ໄປໂຮງຮຽນ', 'transit_transfer': 'ການຖ່າຍໂອນການເດີນທາງ', 'shopping': 'ຊອບປິ້ງ', 'meal': 'ອາຫານ', 'pick_drop_person': 'ໄປຮັບ ຫລື ສົນ ຄົນ', 'pick_drop_item': 'ໄປຮັບ ຫລື ສົ່ງສິນຄ້າ', 'personal_med': 'ໄປຫາໝໍ', 'access_recreation': 'ເຂົ້າເຖິງການພັກຜ່ອນ', 'exercise': 'ພັກຜ່ອນ/ອອກກຳລັງກາຍ', 'entertainment': 'ບັນເທີງ/ສັງຄົມ', 'religious': 'ຈຸດປະສົງທາງສາດສະໜາ', 'other': 'ອື່ນໆ'}}}
use_imperial = True
sensed_algo_prefix = "cleaned"
survey_info = {}

In [2]:
# total 9 plots

In [3]:
import sys
import numpy

print(sys.executable)
print(sys.path)
print(numpy.__version__)
print(numpy.__file__)

/root/miniforge-26.1.1/envs/emission/bin/python
['/usr/src/app', '/root/miniforge-26.1.1/envs/emission/lib/python311.zip', '/root/miniforge-26.1.1/envs/emission/lib/python3.11', '/root/miniforge-26.1.1/envs/emission/lib/python3.11/lib-dynload', '', '/root/miniforge-26.1.1/envs/emission/lib/python3.11/site-packages']
1.24.2
/root/miniforge-26.1.1/envs/emission/lib/python3.11/site-packages/numpy/__init__.py

In [4]:
# test environment/kernel
from collections import defaultdict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from plots import *
import scaffolding

sns.set_style("whitegrid")
sns.set()
%matplotlib inline

DEBUG:matplotlib.pyplot:Loaded backend module://matplotlib_inline.backend_inline version unknown.

Config file not found, returning a copy of the environment variables instead...
Retrieved config: {'DB_HOST': 'mongodb://db/openpath_prod_nrel_commute', 'DB_RESULT_LIMIT': None, 'USE_HINTS': None, 'MONITOR_DB': None}
Connecting to database URL mongodb://db/openpath_prod_nrel_commute

In [5]:
# get metric vs imperial vars
label_units, short_label, label_units_lower, distance_col, weight_unit = scaffolding.get_units(use_imperial)

In [6]:
colors_mode, colors_replaced, colors_purpose, colors_sensed, colors_ble = scaffolding.mapping_color_labels(labels)
values_to_translations_mode, values_to_translations_purpose, values_to_translations_replaced = scaffolding.translate_values_to_labels(labels)

In [7]:
expanded_ct, file_suffix, quality_text, debug_df = await scaffolding.load_viz_notebook_data(year,
                                                                            month,
                                                                            program,
                                                                            study_type,
                                                                            labels,
                                                                            include_test_users=include_test_users,
                                                                            add_footprint=True)

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

DEBUG:root:curr_query = {'invalid': {'$exists': False}, '$or': [{'metadata.key': 'analysis/confirmed_trip'}]}, sort_key = None
DEBUG:root:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/confirmed_trip']
DEBUG:root:finished querying values for [], count = 0
DEBUG:root:finished querying values for ['analysis/confirmed_trip'], count = 14050
DEBUG:root:orig_ts_db_matches = 0, analysis_ts_db_matches = 14050

add_base_mode_footprint running{'MODE': [{'value': 'walk', 'base_mode': 'WALKING'}, {'value': 'e-bike', 'base_mode': 'E_BIKE'}, {'value': 'bike', 'base_mode': 'BICYCLING'}, {'value': 'bikeshare', 'base_mode': 'BICYCLING'}, {'value': 'scootershare', 'base_mode': 'E_SCOOTER'}, {'value': 'drove_alone', 'base_mode': 'CAR', 'passengers': 1}, {'value': 'shared_ride', 'base_mode': 'CAR', 'passengers': 2}, {'value': 'hybrid_drove_alone', 'base_mode': 'PHEV_CAR', 'passengers': 1}, {'value': 'hybrid_shared_ride', 'base_mode': 'PHEV_CAR', 'passengers': 2}, {'value': 'e_car_drove_alone', 'base_mode': 'E_CAR', 'passengers': 1}, {'value': 'e_car_shared_ride', 'base_mode': 'E_CAR', 'passengers': 2}, {'value': 'taxi', 'base_mode': 'TAXI'}, {'value': 'bus', 'base_mode': 'BUS'}, {'value': 'train', 'base_mode': 'TRAIN'}, {'value': 'free_shuttle', 'base_mode': 'BUS'}, {'value': 'air', 'base_mode': 'AIR'}, {'value': 'not_a_trip', 'base_mode': 'UNKNOWN'}, {'value': 'other', 'base_mode': 'OTHER'}], 'PURPOSE': [{'value': 'home'}, {'value': 'work'}, {'value': 'at_work'}, {'value': 'school'}, {'value': 'transit_transfer'}, {'value': 'shopping'}, {'value': 'meal'}, {'value': 'pick_drop_person'}, {'value': 'pick_drop_item'}, {'value': 'personal_med'}, {'value': 'access_recreation'}, {'value': 'exercise'}, {'value': 'entertainment'}, {'value': 'religious'}, {'value': 'other'}], 'REPLACED_MODE': [{'value': 'no_travel'}, {'value': 'walk'}, {'value': 'bike'}, {'value': 'bikeshare'}, {'value': 'scootershare'}, {'value': 'drove_alone'}, {'value': 'shared_ride'}, {'value': 'hybrid_drove_alone'}, {'value': 'hybrid_shared_ride'}, {'value': 'e_car_drove_alone'}, {'value': 'e_car_shared_ride'}, {'value': 'taxi'}, {'value': 'bus'}, {'value': 'train'}, {'value': 'free_shuttle'}, {'value': 'other'}], 'translations': {'en': {'walk': 'Walk', 'e-bike': 'E-bike', 'bike': 'Regular Bike', 'bikeshare': 'Bikeshare', 'scootershare': 'Scooter share', 'drove_alone': 'Gas Car Drove Alone', 'shared_ride': 'Gas Car Shared Ride', 'hybrid_drove_alone': 'Hybrid Drove Alone', 'hybrid_shared_ride': 'Hybrid Shared Ride', 'e_car_drove_alone': 'E-Car Drove Alone', 'e_car_shared_ride': 'E-Car Shared Ride', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Bus', 'train': 'Train', 'free_shuttle': 'Free Shuttle', 'air': 'Air', 'not_a_trip': 'Not a trip', 'no_travel': 'No travel', 'home': 'Home', 'work': 'To Work', 'at_work': 'At Work', 'school': 'School', 'transit_transfer': 'Transit transfer', 'shopping': 'Shopping', 'meal': 'Meal', 'pick_drop_person': 'Pick-up / Drop off Person', 'pick_drop_item': 'Pick-up / Drop off Item', 'personal_med': 'Personal / Medical', 'access_recreation': 'Access Recreation', 'exercise': 'Recreation / Exercise', 'entertainment': 'Entertainment / Social', 'religious': 'Religious', 'other': 'Other'}, 'es': {'walk': 'Caminando', 'e-bike': 'e-bicicleta', 'bike': 'Bicicleta', 'bikeshare': 'Bicicleta compartida', 'scootershare': 'Motoneta compartida', 'drove_alone': 'Coche de Gas, Condujo solo', 'shared_ride': 'Coche de Gas, Condujo con otros', 'hybrid_drove_alone': 'Coche Híbrido, Condujo solo', 'hybrid_shared_ride': 'Coche Híbrido, Condujo con otros', 'e_car_drove_alone': 'e-coche, Condujo solo', 'e_car_shared_ride': 'e-coche, Condujo con otros', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Autobús', 'train': 'Tren', 'free_shuttle': 'Colectivo gratuito', 'air': 'Avión', 'not_a_trip': 'No es un viaje', 'no_travel': 'No viajar', 'home': 'Casa', 'work': 'Trabajo', 'at_work': 'En el trabajo', 'school': 'Escuela', 'transit_transfer': 'Transbordo', 'shopping': 'Compras', 'meal': 'Comida', 'pick_drop_person': 'Recoger / Entregar Individuo', 'pick_drop_item': 'Recoger / Entregar Objeto', 'personal_med': 'Personal / Médico', 'access_recreation': 'Acceder a Recreación', 'exercise': 'Recreación / Ejercicio', 'entertainment': 'Entretenimiento / Social', 'religious': 'Religioso', 'other': 'Otros'}, 'lo': {'walk': 'ດ້ວຍການຍ່າງ', 'e-bike': 'ວຍລົດຈັກໄຟຟ້າ', 'bike': 'ລົດຖີບ', 'bikeshare': 'ດ້ວຍລົດຖີບທີ່ໃຫ້ເຊົ່າ', 'scootershare': 'ດ້ວຍລົດຈັກສະກູດເຕີ້ໃຫ້ເຊົ່າ ', 'drove_alone': 'ເດີນທາງ ດ້ວຍລົດໃຫ່ຍ ເຊີ່ງເປັນລົດທີ່ຂັບເອງ', 'shared_ride': 'ເດີນທາງດ້ວຍລົດໃຫ່ຍ ຮ່ວມກັບລົດຄົນອຶ່ນ', 'hybrid_drove_alone': 'ລົດປະສົມຂັບຄົນດຽວ', 'hybrid_shared_ride': 'ລົດປະສົມທີ່ໃຊ້ຮ່ວມກັນ', 'e_car_drove_alone': 'ດ້ວຍການຂັບລົດໄຟຟ້າໄປເອງ', 'e_car_shared_ride': 'ດ້ວຍການຈ້າງລົດໄຟຟ້າໄປ', 'taxi': 'ແທັກຊີ', 'bus': 'ລົດເມ', 'train': 'ລົດໄຟ', 'free_shuttle': 'ລົດຮັບສົ່ງຟຣີ', 'air': 'ຍົນ', 'not_a_trip': 'ບໍ່ແມ່ນການເດີນທາງ', 'no_travel': 'ບໍ່ມີການເດີນທາງ', 'home': 'ບ້ານ', 'work': 'ໄປເຮັດວຽກ', 'at_work': 'ຢູ່ບ່ອນເຮັດວຽກ', 'school': 'ໄປໂຮງຮຽນ', 'transit_transfer': 'ການຖ່າຍໂອນການເດີນທາງ', 'shopping': 'ຊອບປິ້ງ', 'meal': 'ອາຫານ', 'pick_drop_person': 'ໄປຮັບ ຫລື ສົນ ຄົນ', 'pick_drop_item': 'ໄປຮັບ ຫລື ສົ່ງສິນຄ້າ', 'personal_med': 'ໄປຫາໝໍ', 'access_recreation': 'ເຂົ້າເຖິງການພັກຜ່ອນ', 'exercise': 'ພັກຜ່ອນ/ອອກກຳລັງກາຍ', 'entertainment': 'ບັນເທີງ/ສັງຄົມ', 'religious': 'ຈຸດປະສົງທາງສາດສະໜາ', 'other': 'ອື່ນໆ'}}}
{'MODE': [{'value': 'walk', 'base_mode': 'WALKING'}, {'value': 'e-bike', 'base_mode': 'E_BIKE'}, {'value': 'bike', 'base_mode': 'BICYCLING'}, {'value': 'bikeshare', 'base_mode': 'BICYCLING'}, {'value': 'scootershare', 'base_mode': 'E_SCOOTER'}, {'value': 'drove_alone', 'base_mode': 'CAR', 'passengers': 1}, {'value': 'shared_ride', 'base_mode': 'CAR', 'passengers': 2}, {'value': 'hybrid_drove_alone', 'base_mode': 'PHEV_CAR', 'passengers': 1}, {'value': 'hybrid_shared_ride', 'base_mode': 'PHEV_CAR', 'passengers': 2}, {'value': 'e_car_drove_alone', 'base_mode': 'E_CAR', 'passengers': 1}, {'value': 'e_car_shared_ride', 'base_mode': 'E_CAR', 'passengers': 2}, {'value': 'taxi', 'base_mode': 'TAXI'}, {'value': 'bus', 'base_mode': 'BUS'}, {'value': 'train', 'base_mode': 'TRAIN'}, {'value': 'free_shuttle', 'base_mode': 'BUS'}, {'value': 'air', 'base_mode': 'AIR'}, {'value': 'not_a_trip', 'base_mode': 'UNKNOWN'}, {'value': 'other', 'base_mode': 'OTHER'}], 'PURPOSE': [{'value': 'home'}, {'value': 'work'}, {'value': 'at_work'}, {'value': 'school'}, {'value': 'transit_transfer'}, {'value': 'shopping'}, {'value': 'meal'}, {'value': 'pick_drop_person'}, {'value': 'pick_drop_item'}, {'value': 'personal_med'}, {'value': 'access_recreation'}, {'value': 'exercise'}, {'value': 'entertainment'}, {'value': 'religious'}, {'value': 'other'}], 'REPLACED_MODE': [{'value': 'no_travel'}, {'value': 'walk'}, {'value': 'bike'}, {'value': 'bikeshare'}, {'value': 'scootershare'}, {'value': 'drove_alone'}, {'value': 'shared_ride'}, {'value': 'hybrid_drove_alone'}, {'value': 'hybrid_shared_ride'}, {'value': 'e_car_drove_alone'}, {'value': 'e_car_shared_ride'}, {'value': 'taxi'}, {'value': 'bus'}, {'value': 'train'}, {'value': 'free_shuttle'}, {'value': 'other'}], 'translations': {'en': {'walk': 'Walk', 'e-bike': 'E-bike', 'bike': 'Regular Bike', 'bikeshare': 'Bikeshare', 'scootershare': 'Scooter share', 'drove_alone': 'Gas Car Drove Alone', 'shared_ride': 'Gas Car Shared Ride', 'hybrid_drove_alone': 'Hybrid Drove Alone', 'hybrid_shared_ride': 'Hybrid Shared Ride', 'e_car_drove_alone': 'E-Car Drove Alone', 'e_car_shared_ride': 'E-Car Shared Ride', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Bus', 'train': 'Train', 'free_shuttle': 'Free Shuttle', 'air': 'Air', 'not_a_trip': 'Not a trip', 'no_travel': 'No travel', 'home': 'Home', 'work': 'To Work', 'at_work': 'At Work', 'school': 'School', 'transit_transfer': 'Transit transfer', 'shopping': 'Shopping', 'meal': 'Meal', 'pick_drop_person': 'Pick-up / Drop off Person', 'pick_drop_item': 'Pick-up / Drop off Item', 'personal_med': 'Personal / Medical', 'access_recreation': 'Access Recreation', 'exercise': 'Recreation / Exercise', 'entertainment': 'Entertainment / Social', 'religious': 'Religious', 'other': 'Other'}, 'es': {'walk': 'Caminando', 'e-bike': 'e-bicicleta', 'bike': 'Bicicleta', 'bikeshare': 'Bicicleta compartida', 'scootershare': 'Motoneta compartida', 'drove_alone': 'Coche de Gas, Condujo solo', 'shared_ride': 'Coche de Gas, Condujo con otros', 'hybrid_drove_alone': 'Coche Híbrido, Condujo solo', 'hybrid_shared_ride': 'Coche Híbrido, Condujo con otros', 'e_car_drove_alone': 'e-coche, Condujo solo', 'e_car_shared_ride': 'e-coche, Condujo con otros', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Autobús', 'train': 'Tren', 'free_shuttle': 'Colectivo gratuito', 'air': 'Avión', 'not_a_trip': 'No es un viaje', 'no_travel': 'No viajar', 'home': 'Casa', 'work': 'Trabajo', 'at_work': 'En el trabajo', 'school': 'Escuela', 'transit_transfer': 'Transbordo', 'shopping': 'Compras', 'meal': 'Comida', 'pick_drop_person': 'Recoger / Entregar Individuo', 'pick_drop_item': 'Recoger / Entregar Objeto', 'personal_med': 'Personal / Médico', 'access_recreation': 'Acceder a Recreación', 'exercise': 'Recreación / Ejercicio', 'entertainment': 'Entretenimiento / Social', 'religious': 'Religioso', 'other': 'Otros'}, 'lo': {'walk': 'ດ້ວຍການຍ່າງ', 'e-bike': 'ວຍລົດຈັກໄຟຟ້າ', 'bike': 'ລົດຖີບ', 'bikeshare': 'ດ້ວຍລົດຖີບທີ່ໃຫ້ເຊົ່າ', 'scootershare': 'ດ້ວຍລົດຈັກສະກູດເຕີ້ໃຫ້ເຊົ່າ ', 'drove_alone': 'ເດີນທາງ ດ້ວຍລົດໃຫ່ຍ ເຊີ່ງເປັນລົດທີ່ຂັບເອງ', 'shared_ride': 'ເດີນທາງດ້ວຍລົດໃຫ່ຍ ຮ່ວມກັບລົດຄົນອຶ່ນ', 'hybrid_drove_alone': 'ລົດປະສົມຂັບຄົນດຽວ', 'hybrid_shared_ride': 'ລົດປະສົມທີ່ໃຊ້ຮ່ວມກັນ', 'e_car_drove_alone': 'ດ້ວຍການຂັບລົດໄຟຟ້າໄປເອງ', 'e_car_shared_ride': 'ດ້ວຍການຈ້າງລົດໄຟຟ້າໄປ', 'taxi': 'ແທັກຊີ', 'bus': 'ລົດເມ', 'train': 'ລົດໄຟ', 'free_shuttle': 'ລົດຮັບສົ່ງຟຣີ', 'air': 'ຍົນ', 'not_a_trip': 'ບໍ່ແມ່ນການເດີນທາງ', 'no_travel': 'ບໍ່ມີການເດີນທາງ', 'home': 'ບ້ານ', 'work': 'ໄປເຮັດວຽກ', 'at_work': 'ຢູ່ບ່ອນເຮັດວຽກ', 'school': 'ໄປໂຮງຮຽນ', 'transit_transfer': 'ການຖ່າຍໂອນການເດີນທາງ', 'shopping': 'ຊອບປິ້ງ', 'meal': 'ອາຫານ', 'pick_drop_person': 'ໄປຮັບ ຫລື ສົນ ຄົນ', 'pick_drop_item': 'ໄປຮັບ ຫລື ສົ່ງສິນຄ້າ', 'personal_med': 'ໄປຫາໝໍ', 'access_recreation': 'ເຂົ້າເຖິງການພັກຜ່ອນ', 'exercise': 'ພັກຜ່ອນ/ອອກກຳລັງກາຍ', 'entertainment': 'ບັນເທີງ/ສັງຄົມ', 'religious': 'ຈຸດປະສົງທາງສາດສະໜາ', 'other': 'ອື່ນໆ'}}}
label: MODE
label: PURPOSE
label: REPLACED_MODE
label: translations

WARNING:root:eGRID data not available for 2023. Trying 2022.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8914217&y=37.4090063&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
WARNING:root:ntd data not available for 2023. Trying 2022.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1230487&y=43.0341105&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 502 141
ERROR:root:Failed to geocode [-76.1230487, 43.0341105] in year 2023: Failed to fetch https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-76.1230487&y=43.0341105&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json: {"errors":["The server, while working as a gateway to get a response needed to handle the request, got an invalid response."],"status":"502"}
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1315669&y=43.0373256&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 502 141
ERROR:root:Failed to geocode [-76.1315669, 43.0373256] in year 2023: Failed to fetch https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-76.1315669&y=43.0373256&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json: {"errors":["The server, while working as a gateway to get a response needed to handle the request, got an invalid response."],"status":"502"}
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1347867&y=43.0359594&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4921
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3022941&y=47.6493537&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3031373&y=47.6499199&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3424827&y=47.6493288&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4933
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3387933&y=47.6146157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4928
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3035919&y=47.6501712&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.30178686945014&y=47.65389058796894&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4949
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4391935&y=37.8598731&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4391935, 37.8598731] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4391935&y=37.8598731&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8910895&y=37.4098175&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.30484124585898&y=47.65262782060119&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4947
DEBUG:root:Worst rich mode is taxi with 1198.36 wh_per_km
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3580067802693&y=47.623801545705064&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4945
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.426663&y=37.8700003&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4625
WARNING:root:Urban Area not in geocoding response for coords [-122.426663, 37.8700003] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.426663&y=37.8700003&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4409946&y=37.8566342&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4409946, 37.8566342] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4409946&y=37.8566342&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.076336&y=37.3944835&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4973
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1653766&y=37.4436299&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1703269&y=39.7426673&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4949
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1513431&y=39.7440227&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4946
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0862351&y=37.3903567&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4976
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1663197&y=37.4436843&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4234344&y=37.8556422&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4234344, 37.8556422] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4234344&y=37.8556422&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1663051&y=37.4436984&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0572636&y=37.6345475&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4986
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.08619&y=37.3903998&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3932211&y=37.7967814&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4711
WARNING:root:Urban Area not in geocoding response for coords [-122.3932211, 37.7967814] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.3932211&y=37.7967814&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3279116&y=47.5934768&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4926
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0888588&y=37.3881385&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4074305&y=37.7842445&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5090
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.111064&y=37.3996921&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4961
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4226519&y=37.7647984&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5018
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1658035&y=37.4437073&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4194957&y=37.7917525&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5093
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4330824&y=37.8648157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4330824, 37.8648157] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4330824&y=37.8648157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4753907&y=37.8066502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5044
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3925857&y=37.6159806&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4554
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3010067&y=47.4444967&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4926
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0767048&y=37.39502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4978
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4342361&y=37.8674001&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4342361, 37.8674001] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4342361&y=37.8674001&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3937091&y=37.796155&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5089
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3941031&y=37.7760694&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5047
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0865742&y=37.3910397&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4975
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0309042&y=37.4110223&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4978
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0765487&y=37.394448&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4973
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-74.1768399&y=40.6950539&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4980
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.9416371&y=37.4106187&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8917685&y=37.4092032&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1269796&y=37.6972924&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4983
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0874259&y=37.3873467&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4984
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0313128&y=37.3661384&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1731358&y=39.7388502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4954

Loaded all confirmed trips of length 14050

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,8,4,21,7,58,4,America/New_York,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,3,20,12,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

After filtering, found 14050 participant trips

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,8,4,21,7,58,4,America/New_York,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,3,20,12,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

After filtering, found 5279 labeled trips

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
8,DwellSegmentationTimeFilter,1.667264e+09,2022-10-31T17:56:37-07:00,"{'type': 'Point', 'coordinates': [-122.0387509...",6360764a202d3859715ff290,1.667264e+09,2022-10-31T17:48:12.011045-07:00,"{'type': 'Point', 'coordinates': [-122.0370089...",504.988955,191.899114,...,10,31,17,56,37,0,America/Los_Angeles,df96f1df-7eb5-4499-a09e-71070a5a089e,1.667266e+09,NaN
9,DwellSegmentationDistFilter,1.692064e+09,2023-08-14T19:53:13.962959-06:00,"{'type': 'Point', 'coordinates': [-105.2125013...",64dae618342009cb8697da2c,1.692063e+09,2023-08-14T19:33:13.833949-06:00,"{'type': 'Point', 'coordinates': [-105.2273043...",1200.129009,4666.552271,...,8,14,19,53,13,0,America/Denver,02866eed-9533-4db9-b8ed-eccb1ee7f10f,1.692068e+09,NaN

    purpose_confirm mode_confirm trip_user_input
0              meal  drove_alone             NaN
1  pick_drop_person  shared_ride             NaN
2              work  drove_alone             NaN
8          exercise         walk             NaN
9              work  drove_alone             NaN

Found Index(['purpose_confirm', 'mode_confirm', 'trip_user_input'], dtype='object') columns of length 3
After expanding, columns went from 47 -> 50

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary,purpose_confirm,mode_confirm,trip_user_input
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN,meal,drove_alone,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN,pick_drop_person,shared_ride,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN,work,drove_alone,NaN
8,DwellSegmentationTimeFilter,1.667264e+09,2022-10-31T17:56:37-07:00,"{'type': 'Point', 'coordinates': [-122.0387509...",6360764a202d3859715ff290,1.667264e+09,2022-10-31T17:48:12.011045-07:00,"{'type': 'Point', 'coordinates': [-122.0370089...",504.988955,191.899114,...,56,37,0,America/Los_Angeles,df96f1df-7eb5-4499-a09e-71070a5a089e,1.667266e+09,NaN,exercise,walk,NaN
9,DwellSegmentationDistFilter,1.692064e+09,2023-08-14T19:53:13.962959-06:00,"{'type': 'Point', 'coordinates': [-105.2125013...",64dae618342009cb8697da2c,1.692063e+09,2023-08-14T19:33:13.833949-06:00,"{'type': 'Point', 'coordinates': [-105.2273043...",1200.129009,4666.552271,...,53,13,0,America/Denver,02866eed-9533-4db9-b8ed-eccb1ee7f10f,1.692068e+09,NaN,work,drove_alone,NaN

This is a study, not expecting any replaced modes.
_default
Based on 5279 confirmed trips from 25 users
of 14050 total  trips from 30 users (37.57%)

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

In [8]:
expanded_ct_sensed, file_suffix_sensed, quality_text_sensed, debug_df_sensed = await scaffolding.load_viz_notebook_sensor_inference_data(year,
                                                                            month,
                                                                            program,
                                                                            labels,
                                                                            include_test_users,
                                                                            sensed_algo_prefix)

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

DEBUG:root:curr_query = {'invalid': {'$exists': False}, '$or': [{'metadata.key': 'analysis/confirmed_trip'}]}, sort_key = None
DEBUG:root:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/confirmed_trip']
DEBUG:root:finished querying values for [], count = 0
DEBUG:root:finished querying values for ['analysis/confirmed_trip'], count = 14050
DEBUG:root:orig_ts_db_matches = 0, analysis_ts_db_matches = 14050
DEBUG:root:Found 14050 results
DEBUG:root:After de-duping, converted 14050 points to 14050

Loaded all confirmed trips of length 14050

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,_id,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,17,12,27,6,2,America/Denver,62fd3431798a2d554803bc40,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,18,18,13,8,3,America/New_York,6466b5789b3fa7fa27cc1937,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,22,17,22,41,3,America/Denver,632cf602e1d03379afd8a358,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,4,21,7,58,4,America/New_York,64cdb4d68a06e74aed62046a,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,20,12,37,56,0,America/Denver,6418b69c0ef654a9da765bcd,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

After filtering, found 14050 participant trips

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,_id,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,17,12,27,6,2,America/Denver,62fd3431798a2d554803bc40,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,18,18,13,8,3,America/New_York,6466b5789b3fa7fa27cc1937,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,22,17,22,41,3,America/Denver,632cf602e1d03379afd8a358,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,4,21,7,58,4,America/New_York,64cdb4d68a06e74aed62046a,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,20,12,37,56,0,America/Denver,6418b69c0ef654a9da765bcd,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

Loaded expanded_ct with length 14050 for None
_default
Based on 14050 trips from 30 users

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

In [9]:
expanded_ct_inferred, file_suffix_inferred, quality_text_inferred, debug_df_inferred = await scaffolding.load_viz_notebook_inferred_data(year,
                                                                            month,
                                                                            program,
                                                                            study_type,
                                                                            labels,
                                                                            include_test_users=include_test_users,
                                                                            add_footprint=True)

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

DEBUG:root:curr_query = {'invalid': {'$exists': False}, '$or': [{'metadata.key': 'analysis/confirmed_trip'}]}, sort_key = None
DEBUG:root:orig_ts_db_keys = [], analysis_ts_db_keys = ['analysis/confirmed_trip']
DEBUG:root:finished querying values for [], count = 0
DEBUG:root:finished querying values for ['analysis/confirmed_trip'], count = 14050
DEBUG:root:orig_ts_db_matches = 0, analysis_ts_db_matches = 14050
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443

add_base_mode_footprint running{'MODE': [{'value': 'walk', 'base_mode': 'WALKING'}, {'value': 'e-bike', 'base_mode': 'E_BIKE'}, {'value': 'bike', 'base_mode': 'BICYCLING'}, {'value': 'bikeshare', 'base_mode': 'BICYCLING'}, {'value': 'scootershare', 'base_mode': 'E_SCOOTER'}, {'value': 'drove_alone', 'base_mode': 'CAR', 'passengers': 1}, {'value': 'shared_ride', 'base_mode': 'CAR', 'passengers': 2}, {'value': 'hybrid_drove_alone', 'base_mode': 'PHEV_CAR', 'passengers': 1}, {'value': 'hybrid_shared_ride', 'base_mode': 'PHEV_CAR', 'passengers': 2}, {'value': 'e_car_drove_alone', 'base_mode': 'E_CAR', 'passengers': 1}, {'value': 'e_car_shared_ride', 'base_mode': 'E_CAR', 'passengers': 2}, {'value': 'taxi', 'base_mode': 'TAXI'}, {'value': 'bus', 'base_mode': 'BUS'}, {'value': 'train', 'base_mode': 'TRAIN'}, {'value': 'free_shuttle', 'base_mode': 'BUS'}, {'value': 'air', 'base_mode': 'AIR'}, {'value': 'not_a_trip', 'base_mode': 'UNKNOWN'}, {'value': 'other', 'base_mode': 'OTHER'}], 'PURPOSE': [{'value': 'home'}, {'value': 'work'}, {'value': 'at_work'}, {'value': 'school'}, {'value': 'transit_transfer'}, {'value': 'shopping'}, {'value': 'meal'}, {'value': 'pick_drop_person'}, {'value': 'pick_drop_item'}, {'value': 'personal_med'}, {'value': 'access_recreation'}, {'value': 'exercise'}, {'value': 'entertainment'}, {'value': 'religious'}, {'value': 'other'}], 'REPLACED_MODE': [{'value': 'no_travel'}, {'value': 'walk'}, {'value': 'bike'}, {'value': 'bikeshare'}, {'value': 'scootershare'}, {'value': 'drove_alone'}, {'value': 'shared_ride'}, {'value': 'hybrid_drove_alone'}, {'value': 'hybrid_shared_ride'}, {'value': 'e_car_drove_alone'}, {'value': 'e_car_shared_ride'}, {'value': 'taxi'}, {'value': 'bus'}, {'value': 'train'}, {'value': 'free_shuttle'}, {'value': 'other'}], 'translations': {'en': {'walk': 'Walk', 'e-bike': 'E-bike', 'bike': 'Regular Bike', 'bikeshare': 'Bikeshare', 'scootershare': 'Scooter share', 'drove_alone': 'Gas Car Drove Alone', 'shared_ride': 'Gas Car Shared Ride', 'hybrid_drove_alone': 'Hybrid Drove Alone', 'hybrid_shared_ride': 'Hybrid Shared Ride', 'e_car_drove_alone': 'E-Car Drove Alone', 'e_car_shared_ride': 'E-Car Shared Ride', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Bus', 'train': 'Train', 'free_shuttle': 'Free Shuttle', 'air': 'Air', 'not_a_trip': 'Not a trip', 'no_travel': 'No travel', 'home': 'Home', 'work': 'To Work', 'at_work': 'At Work', 'school': 'School', 'transit_transfer': 'Transit transfer', 'shopping': 'Shopping', 'meal': 'Meal', 'pick_drop_person': 'Pick-up / Drop off Person', 'pick_drop_item': 'Pick-up / Drop off Item', 'personal_med': 'Personal / Medical', 'access_recreation': 'Access Recreation', 'exercise': 'Recreation / Exercise', 'entertainment': 'Entertainment / Social', 'religious': 'Religious', 'other': 'Other'}, 'es': {'walk': 'Caminando', 'e-bike': 'e-bicicleta', 'bike': 'Bicicleta', 'bikeshare': 'Bicicleta compartida', 'scootershare': 'Motoneta compartida', 'drove_alone': 'Coche de Gas, Condujo solo', 'shared_ride': 'Coche de Gas, Condujo con otros', 'hybrid_drove_alone': 'Coche Híbrido, Condujo solo', 'hybrid_shared_ride': 'Coche Híbrido, Condujo con otros', 'e_car_drove_alone': 'e-coche, Condujo solo', 'e_car_shared_ride': 'e-coche, Condujo con otros', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Autobús', 'train': 'Tren', 'free_shuttle': 'Colectivo gratuito', 'air': 'Avión', 'not_a_trip': 'No es un viaje', 'no_travel': 'No viajar', 'home': 'Casa', 'work': 'Trabajo', 'at_work': 'En el trabajo', 'school': 'Escuela', 'transit_transfer': 'Transbordo', 'shopping': 'Compras', 'meal': 'Comida', 'pick_drop_person': 'Recoger / Entregar Individuo', 'pick_drop_item': 'Recoger / Entregar Objeto', 'personal_med': 'Personal / Médico', 'access_recreation': 'Acceder a Recreación', 'exercise': 'Recreación / Ejercicio', 'entertainment': 'Entretenimiento / Social', 'religious': 'Religioso', 'other': 'Otros'}, 'lo': {'walk': 'ດ້ວຍການຍ່າງ', 'e-bike': 'ວຍລົດຈັກໄຟຟ້າ', 'bike': 'ລົດຖີບ', 'bikeshare': 'ດ້ວຍລົດຖີບທີ່ໃຫ້ເຊົ່າ', 'scootershare': 'ດ້ວຍລົດຈັກສະກູດເຕີ້ໃຫ້ເຊົ່າ ', 'drove_alone': 'ເດີນທາງ ດ້ວຍລົດໃຫ່ຍ ເຊີ່ງເປັນລົດທີ່ຂັບເອງ', 'shared_ride': 'ເດີນທາງດ້ວຍລົດໃຫ່ຍ ຮ່ວມກັບລົດຄົນອຶ່ນ', 'hybrid_drove_alone': 'ລົດປະສົມຂັບຄົນດຽວ', 'hybrid_shared_ride': 'ລົດປະສົມທີ່ໃຊ້ຮ່ວມກັນ', 'e_car_drove_alone': 'ດ້ວຍການຂັບລົດໄຟຟ້າໄປເອງ', 'e_car_shared_ride': 'ດ້ວຍການຈ້າງລົດໄຟຟ້າໄປ', 'taxi': 'ແທັກຊີ', 'bus': 'ລົດເມ', 'train': 'ລົດໄຟ', 'free_shuttle': 'ລົດຮັບສົ່ງຟຣີ', 'air': 'ຍົນ', 'not_a_trip': 'ບໍ່ແມ່ນການເດີນທາງ', 'no_travel': 'ບໍ່ມີການເດີນທາງ', 'home': 'ບ້ານ', 'work': 'ໄປເຮັດວຽກ', 'at_work': 'ຢູ່ບ່ອນເຮັດວຽກ', 'school': 'ໄປໂຮງຮຽນ', 'transit_transfer': 'ການຖ່າຍໂອນການເດີນທາງ', 'shopping': 'ຊອບປິ້ງ', 'meal': 'ອາຫານ', 'pick_drop_person': 'ໄປຮັບ ຫລື ສົນ ຄົນ', 'pick_drop_item': 'ໄປຮັບ ຫລື ສົ່ງສິນຄ້າ', 'personal_med': 'ໄປຫາໝໍ', 'access_recreation': 'ເຂົ້າເຖິງການພັກຜ່ອນ', 'exercise': 'ພັກຜ່ອນ/ອອກກຳລັງກາຍ', 'entertainment': 'ບັນເທີງ/ສັງຄົມ', 'religious': 'ຈຸດປະສົງທາງສາດສະໜາ', 'other': 'ອື່ນໆ'}}}
{'MODE': [{'value': 'walk', 'base_mode': 'WALKING'}, {'value': 'e-bike', 'base_mode': 'E_BIKE'}, {'value': 'bike', 'base_mode': 'BICYCLING'}, {'value': 'bikeshare', 'base_mode': 'BICYCLING'}, {'value': 'scootershare', 'base_mode': 'E_SCOOTER'}, {'value': 'drove_alone', 'base_mode': 'CAR', 'passengers': 1}, {'value': 'shared_ride', 'base_mode': 'CAR', 'passengers': 2}, {'value': 'hybrid_drove_alone', 'base_mode': 'PHEV_CAR', 'passengers': 1}, {'value': 'hybrid_shared_ride', 'base_mode': 'PHEV_CAR', 'passengers': 2}, {'value': 'e_car_drove_alone', 'base_mode': 'E_CAR', 'passengers': 1}, {'value': 'e_car_shared_ride', 'base_mode': 'E_CAR', 'passengers': 2}, {'value': 'taxi', 'base_mode': 'TAXI'}, {'value': 'bus', 'base_mode': 'BUS'}, {'value': 'train', 'base_mode': 'TRAIN'}, {'value': 'free_shuttle', 'base_mode': 'BUS'}, {'value': 'air', 'base_mode': 'AIR'}, {'value': 'not_a_trip', 'base_mode': 'UNKNOWN'}, {'value': 'other', 'base_mode': 'OTHER'}], 'PURPOSE': [{'value': 'home'}, {'value': 'work'}, {'value': 'at_work'}, {'value': 'school'}, {'value': 'transit_transfer'}, {'value': 'shopping'}, {'value': 'meal'}, {'value': 'pick_drop_person'}, {'value': 'pick_drop_item'}, {'value': 'personal_med'}, {'value': 'access_recreation'}, {'value': 'exercise'}, {'value': 'entertainment'}, {'value': 'religious'}, {'value': 'other'}], 'REPLACED_MODE': [{'value': 'no_travel'}, {'value': 'walk'}, {'value': 'bike'}, {'value': 'bikeshare'}, {'value': 'scootershare'}, {'value': 'drove_alone'}, {'value': 'shared_ride'}, {'value': 'hybrid_drove_alone'}, {'value': 'hybrid_shared_ride'}, {'value': 'e_car_drove_alone'}, {'value': 'e_car_shared_ride'}, {'value': 'taxi'}, {'value': 'bus'}, {'value': 'train'}, {'value': 'free_shuttle'}, {'value': 'other'}], 'translations': {'en': {'walk': 'Walk', 'e-bike': 'E-bike', 'bike': 'Regular Bike', 'bikeshare': 'Bikeshare', 'scootershare': 'Scooter share', 'drove_alone': 'Gas Car Drove Alone', 'shared_ride': 'Gas Car Shared Ride', 'hybrid_drove_alone': 'Hybrid Drove Alone', 'hybrid_shared_ride': 'Hybrid Shared Ride', 'e_car_drove_alone': 'E-Car Drove Alone', 'e_car_shared_ride': 'E-Car Shared Ride', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Bus', 'train': 'Train', 'free_shuttle': 'Free Shuttle', 'air': 'Air', 'not_a_trip': 'Not a trip', 'no_travel': 'No travel', 'home': 'Home', 'work': 'To Work', 'at_work': 'At Work', 'school': 'School', 'transit_transfer': 'Transit transfer', 'shopping': 'Shopping', 'meal': 'Meal', 'pick_drop_person': 'Pick-up / Drop off Person', 'pick_drop_item': 'Pick-up / Drop off Item', 'personal_med': 'Personal / Medical', 'access_recreation': 'Access Recreation', 'exercise': 'Recreation / Exercise', 'entertainment': 'Entertainment / Social', 'religious': 'Religious', 'other': 'Other'}, 'es': {'walk': 'Caminando', 'e-bike': 'e-bicicleta', 'bike': 'Bicicleta', 'bikeshare': 'Bicicleta compartida', 'scootershare': 'Motoneta compartida', 'drove_alone': 'Coche de Gas, Condujo solo', 'shared_ride': 'Coche de Gas, Condujo con otros', 'hybrid_drove_alone': 'Coche Híbrido, Condujo solo', 'hybrid_shared_ride': 'Coche Híbrido, Condujo con otros', 'e_car_drove_alone': 'e-coche, Condujo solo', 'e_car_shared_ride': 'e-coche, Condujo con otros', 'taxi': 'Taxi / Uber / Lyft', 'bus': 'Autobús', 'train': 'Tren', 'free_shuttle': 'Colectivo gratuito', 'air': 'Avión', 'not_a_trip': 'No es un viaje', 'no_travel': 'No viajar', 'home': 'Casa', 'work': 'Trabajo', 'at_work': 'En el trabajo', 'school': 'Escuela', 'transit_transfer': 'Transbordo', 'shopping': 'Compras', 'meal': 'Comida', 'pick_drop_person': 'Recoger / Entregar Individuo', 'pick_drop_item': 'Recoger / Entregar Objeto', 'personal_med': 'Personal / Médico', 'access_recreation': 'Acceder a Recreación', 'exercise': 'Recreación / Ejercicio', 'entertainment': 'Entretenimiento / Social', 'religious': 'Religioso', 'other': 'Otros'}, 'lo': {'walk': 'ດ້ວຍການຍ່າງ', 'e-bike': 'ວຍລົດຈັກໄຟຟ້າ', 'bike': 'ລົດຖີບ', 'bikeshare': 'ດ້ວຍລົດຖີບທີ່ໃຫ້ເຊົ່າ', 'scootershare': 'ດ້ວຍລົດຈັກສະກູດເຕີ້ໃຫ້ເຊົ່າ ', 'drove_alone': 'ເດີນທາງ ດ້ວຍລົດໃຫ່ຍ ເຊີ່ງເປັນລົດທີ່ຂັບເອງ', 'shared_ride': 'ເດີນທາງດ້ວຍລົດໃຫ່ຍ ຮ່ວມກັບລົດຄົນອຶ່ນ', 'hybrid_drove_alone': 'ລົດປະສົມຂັບຄົນດຽວ', 'hybrid_shared_ride': 'ລົດປະສົມທີ່ໃຊ້ຮ່ວມກັນ', 'e_car_drove_alone': 'ດ້ວຍການຂັບລົດໄຟຟ້າໄປເອງ', 'e_car_shared_ride': 'ດ້ວຍການຈ້າງລົດໄຟຟ້າໄປ', 'taxi': 'ແທັກຊີ', 'bus': 'ລົດເມ', 'train': 'ລົດໄຟ', 'free_shuttle': 'ລົດຮັບສົ່ງຟຣີ', 'air': 'ຍົນ', 'not_a_trip': 'ບໍ່ແມ່ນການເດີນທາງ', 'no_travel': 'ບໍ່ມີການເດີນທາງ', 'home': 'ບ້ານ', 'work': 'ໄປເຮັດວຽກ', 'at_work': 'ຢູ່ບ່ອນເຮັດວຽກ', 'school': 'ໄປໂຮງຮຽນ', 'transit_transfer': 'ການຖ່າຍໂອນການເດີນທາງ', 'shopping': 'ຊອບປິ້ງ', 'meal': 'ອາຫານ', 'pick_drop_person': 'ໄປຮັບ ຫລື ສົນ ຄົນ', 'pick_drop_item': 'ໄປຮັບ ຫລື ສົ່ງສິນຄ້າ', 'personal_med': 'ໄປຫາໝໍ', 'access_recreation': 'ເຂົ້າເຖິງການພັກຜ່ອນ', 'exercise': 'ພັກຜ່ອນ/ອອກກຳລັງກາຍ', 'entertainment': 'ບັນເທີງ/ສັງຄົມ', 'religious': 'ຈຸດປະສົງທາງສາດສະໜາ', 'other': 'ອື່ນໆ'}}}
label: MODE
label: PURPOSE
label: REPLACED_MODE
label: translations

DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8914217&y=37.4090063&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1230487&y=43.0341105&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4923
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1315669&y=43.0373256&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4921
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-76.1347867&y=43.0359594&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4921
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3022941&y=47.6493537&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3031373&y=47.6499199&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3424827&y=47.6493288&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4933
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3387933&y=47.6146157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4928
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3035919&y=47.6501712&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4935
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.30178686945014&y=47.65389058796894&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4949
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4391935&y=37.8598731&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4391935, 37.8598731] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4391935&y=37.8598731&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8910895&y=37.4098175&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.30484124585898&y=47.65262782060119&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4947
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3580067802693&y=47.623801545705064&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4945
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.426663&y=37.8700003&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4625
WARNING:root:Urban Area not in geocoding response for coords [-122.426663, 37.8700003] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.426663&y=37.8700003&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4409946&y=37.8566342&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4409946, 37.8566342] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4409946&y=37.8566342&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.076336&y=37.3944835&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4973
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1653766&y=37.4436299&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1703269&y=39.7426673&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4949
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1513431&y=39.7440227&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4946
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0862351&y=37.3903567&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4976
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1663197&y=37.4436843&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4234344&y=37.8556422&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4234344, 37.8556422] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4234344&y=37.8556422&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1663051&y=37.4436984&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0572636&y=37.6345475&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4986
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.08619&y=37.3903998&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3932211&y=37.7967814&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4711
WARNING:root:Urban Area not in geocoding response for coords [-122.3932211, 37.7967814] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.3932211&y=37.7967814&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3279116&y=47.5934768&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4926
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0888588&y=37.3881385&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4074305&y=37.7842445&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5090
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.111064&y=37.3996921&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4961
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4226519&y=37.7647984&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5018
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1658035&y=37.4437073&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4974
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4194957&y=37.7917525&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5093
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4330824&y=37.8648157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4330824, 37.8648157] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4330824&y=37.8648157&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
WARNING:root:Unknown fuel type: other
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4753907&y=37.8066502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5044
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3925857&y=37.6159806&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4554
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3010067&y=47.4444967&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4926
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0767048&y=37.39502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4978
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.4342361&y=37.8674001&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4626
WARNING:root:Urban Area not in geocoding response for coords [-122.4342361, 37.8674001] in year 2022: https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=-122.4342361&y=37.8674001&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3937091&y=37.796155&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5089
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.3941031&y=37.7760694&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 5047
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0865742&y=37.3910397&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4975
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0309042&y=37.4110223&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4978
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0765487&y=37.394448&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4973
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-74.1768399&y=40.6950539&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4980
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.9416371&y=37.4106187&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-121.8917685&y=37.4092032&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4966
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.1269796&y=37.6972924&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4983
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0874259&y=37.3873467&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4984
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0313128&y=37.3661384&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-105.1731358&y=39.7388502&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4954
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0317719&y=37.3676067&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4973
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0865343&y=37.3910595&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4975
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443
DEBUG:urllib3.connectionpool:https://geocoding.geo.census.gov:443 "GET /geocoder/geographies/coordinates?x=-122.0319049&y=37.3656834&benchmark=Public_AR_Current&vintage=Census2020_Current&layers=87&format=json HTTP/1.1" 200 4972
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): geocoding.geo.census.gov:443

Loaded all confirmed trips of length 14050

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,8,4,21,7,58,4,America/New_York,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,3,20,12,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

After filtering, found 14050 participant trips

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
3,DwellSegmentationTimeFilter,1.691198e+09,2023-08-04T21:07:58.002000-04:00,"{'type': 'Point', 'coordinates': [-76.1185565,...",64cdb48e8a06e74aed6203f1,1.691197e+09,2023-08-04T20:55:14.001000-04:00,"{'type': 'Point', 'coordinates': [-76.1191335,...",764.001000,161.168304,...,8,4,21,7,58,4,America/New_York,fdce10d2-5456-41e8-93d4-108a7bbc4b1d,1.691203e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,3,20,12,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN

After filtering, found 7568 inferred trips

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_month,end_local_dt_day,end_local_dt_hour,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,8,17,12,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,5,18,18,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,9,22,17,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,3,20,12,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN
8,DwellSegmentationTimeFilter,1.667264e+09,2022-10-31T17:56:37-07:00,"{'type': 'Point', 'coordinates': [-122.0387509...",6360764a202d3859715ff290,1.667264e+09,2022-10-31T17:48:12.011045-07:00,"{'type': 'Point', 'coordinates': [-122.0370089...",504.988955,191.899114,...,10,31,17,56,37,0,America/Los_Angeles,df96f1df-7eb5-4499-a09e-71070a5a089e,1.667266e+09,NaN

    purpose_confirm mode_confirm trip_user_input
0              meal  drove_alone             NaN
1  pick_drop_person  shared_ride             NaN
2              work  drove_alone             NaN
4              work  drove_alone             NaN
8          exercise         walk             NaN

,source,end_ts,end_fmt_time,end_loc,raw_trip,start_ts,start_fmt_time,start_loc,duration,distance,...,end_local_dt_minute,end_local_dt_second,end_local_dt_weekday,end_local_dt_timezone,user_id,metadata_write_ts,ble_sensed_summary,purpose_confirm,mode_confirm,trip_user_input
0,DwellSegmentationDistFilter,1.660761e+09,2022-08-17T12:27:06.999704-06:00,"{'type': 'Point', 'coordinates': [-104.9029413...",62fd33d7798a2d554803bc03,1.660760e+09,2022-08-17T12:08:42.894205-06:00,"{'type': 'Point', 'coordinates': [-104.9268415...",1104.105499,3307.651421,...,27,6,2,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.660761e+09,NaN,meal,drove_alone,NaN
1,DwellSegmentationTimeFilter,1.684448e+09,2023-05-18T18:13:08.361000-04:00,"{'type': 'Point', 'coordinates': [-84.7635346,...",6466b5539b3fa7fa27cc190e,1.684447e+09,2023-05-18T18:04:58.514000-04:00,"{'type': 'Point', 'coordinates': [-84.794358, ...",489.847000,4050.132507,...,13,8,3,America/New_York,71d6fa29-f596-4b3a-920e-67680f423537,1.684453e+09,NaN,pick_drop_person,shared_ride,NaN
2,DwellSegmentationDistFilter,1.663889e+09,2022-09-22T17:22:41.999535-06:00,"{'type': 'Point', 'coordinates': [-105.1748548...",632cf46ce1d03379afd8a337,1.663889e+09,2022-09-22T17:17:24.728153-06:00,"{'type': 'Point', 'coordinates': [-105.1711484...",317.271382,495.393711,...,22,41,3,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.663891e+09,NaN,work,drove_alone,NaN
4,DwellSegmentationDistFilter,1.679337e+09,2023-03-20T12:37:56.011028-06:00,"{'type': 'Point', 'coordinates': [-105.1733437...",6418b6450ef654a9da765b56,1.679337e+09,2023-03-20T12:26:49.413646-06:00,"{'type': 'Point', 'coordinates': [-105.1241268...",666.597382,4581.847918,...,37,56,0,America/Denver,62c29c30-18ec-4398-8ddd-abcfd963e14e,1.679341e+09,NaN,work,drove_alone,NaN
8,DwellSegmentationTimeFilter,1.667264e+09,2022-10-31T17:56:37-07:00,"{'type': 'Point', 'coordinates': [-122.0387509...",6360764a202d3859715ff290,1.667264e+09,2022-10-31T17:48:12.011045-07:00,"{'type': 'Point', 'coordinates': [-122.0370089...",504.988955,191.899114,...,56,37,0,America/Los_Angeles,df96f1df-7eb5-4499-a09e-71070a5a089e,1.667266e+09,NaN,exercise,walk,NaN

This is a study, not expecting any replaced modes.
_default
Based on 6669 confirmed trips from 25 users
of 14050 total  trips from 30 users (47.47%)

0     nrelop_nrel-commute_wAcZAMBHWyhcJVUW5g0aX8B2kx...
1                                      yiaONol02JpBl6Sj
2                                      zfB8q58lhPQNIvmE
3                                      KP11zGjVq3I0TG8Z
4     nrelop_nrel-commute_EaXeUhrSxDgt7uDDZfPGIiOYJI...
5                                      sbSYz7qE1CfkZA3m
6                                      E5hC4ejaSoq6aYaW
7                  nrelop_nrel-commute_c6rpxFVyYZt52MTE
8                  nrelop_nrel-commute_m6LxXMQNYr6RzrKw
9                  nrelop_nrel-commute_aiWo1wRLSmXB0yBk
10    nrelop_nrel-commute_CMFEkaTALEsOnXvpm9PFqXkZqg...
11                 nrelop_nrel-commute_vo1FCK5StN3UnW8E
12                 nrelop_nrel-commute_3J3ltS3IqG2lQsZ0
13                 nrelop_nrel-commute_WwApAHciV0saxV8i
14                              nrelop_nrel-commute_Abc
15                 nrelop_nrel-commute_spwX5YsdgURRs1hB
16                 nrelop_nrel-commute_ASpFzMbNpcTyeTMg
17                       nrelop_dev-emulator-program_pg
18    nrelop_nrel-commute_QbF9fMdMj7M57DyCZHiCAtZJoR...
19    nrelop_nrel-commute_default_pfybRajrNJIAdRO9IR...
20    nrelop_nrel-commute_jd7pmQQccoqrgjoOromP3vMPbO...
21                 nrelop_nrel-commute_sI1RM1GvnWQp61Iv
22    nrelop_nrel-commute_default_ZyQuJZJczmi8LIBjkx...
23    nrelop_nrel-commute_default_IakUayxuTveRxOjPAj...
24    nrelop_nrel-commute_jMRtPwTFhAVE0qi0nzzcZrpjal...
25    nrelop_nrel-commute_uaeQHUOLYYh6x4n7YsiSbjNBnm...
26    nrelop_nrel-commute_l1urcUX9JcdVIWzV9JjuMTilcS...
27    nrelop_nrel-commute_fYsciV5ttojUzmWBoulSjwacQe...
28    nrelop_nrel-commute_fYsci5vttojUzmWBoulhSjwacQ...
29    nrelop_nrel-commute_default_APtNCNptxRWEOo6Zly...
30    nrelop_nrel-commute_fYsciV5vttojUzmWBoulhSjwac...
31    nrelop_nrel-commute_fYsciV5vttojUzmWboulhSjwac...
32    nrelop_nrel-commute_default_S63YIS8dKvM8aMaWfa...
33                     nrelop_dev-emulator-program_D-50
34    nrelop_nrel-commute_default_DvjRf19xOfNaU0tPsM...
35    nrelop_nrel-commute_qT3zYxA5HJvnOInN nrelop_nr...
36    nrelop_nrel-commute_default_PhCG6Cer1OLVumQpPd...
37    nrelop_nrel-commute_default_xwSftOV8oOSVpA5MQk...
38    nrelop_nrel-commute_default_0bktQuwDiROTwxzrg7...
39    nrelop_nrel-commute_default_JXJ3ZX560xYiWOE3Do...
40                 nrelop_nrel-commute_qT3zYxA5HJvnOInN
41    nrelop_nrel-commute_default_DvjR£19x0fNaY0tPsM...
42    nrelop_nrel-commute_default_RZNPwvIUoJplVZjfhm...
43    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
44    nrelop_nrel-commute_DvjRf19xOfNaY0tPsMZgvbmA3N...
45    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
46    nrelop_nrel-commute_fYsciV5vttojUzmWBouIhSjwac...
47    nrelop_nrel-commute_default_DvjRf19xOfNaY0tPsM...
48    nrelop_nrel-commute_default_tfhH8D1aabFhDDjm0E...
49    nrelop_nrel-commute_default_QhAON1enIxsIzrfqCR...
50    nrelop_nrel-commute_default_5361GZDM6WSNikrXnM...
Name: user_email, dtype: object

In [10]:
merged_debug_df = debug_df.combine_first(debug_df_sensed)

In [11]:
quality_text, quality_text_sensed

('Based on 5279 confirmed trips from 25 users\nof 14050 total  trips from 30 users (37.57%)',
 'Based on 14050 trips from 30 users')

In [12]:
import re
labeled_match = re.match(r'Based on ([0-9]+) confirmed trips from ([0-9]+) (users|testers and participants)\nof ([0-9]+) total  trips from ([0-9]+) (users|testers and participants) (\(([0-9.]+|nan)%\))', quality_text)
# labeled_match
stacked_bar_quality_text_labeled = f"{labeled_match.group(1)} trips {labeled_match.group(7)}\n from {labeled_match.group(2)} {labeled_match.group(3)}"

sensed_match = re.match(r'Based on ([0-9]+) trips from ([0-9]+) (users|testers and participants)', quality_text_sensed)
stacked_bar_quality_text_sensed = f"{sensed_match.group(1)} trips (100%)\n from {sensed_match.group(2)} {sensed_match.group(3)}"

inferred_match = re.match(r'Based on ([0-9]+) confirmed trips from ([0-9]+) (users|testers and participants)\nof ([0-9]+) total  trips from ([0-9]+) (users|testers and participants) (\(([0-9.]+|nan)%\))', quality_text_inferred)
stacked_bar_quality_text_inferred = f"{inferred_match.group(1)} trips {inferred_match.group(7)}\n from {inferred_match.group(2)} {inferred_match.group(3)}"

stacked_bar_quality_text_labeled, stacked_bar_quality_text_sensed, stacked_bar_quality_text_inferred

('5279 trips (37.57%)\n from 25 users',
 '14050 trips (100%)\n from 30 users',
 '6669 trips (47.47%)\n from 25 users')

In [13]:
#######################

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
    
# Row bar plots assume percentages
def make_single_row_panel(modes, percents, colors, panel_label, legend_group, legend_group_title):
    traces = []
    for mode, pct in zip(modes, percents):
        traces.append(
            go.Bar(
                y=[panel_label],
                x=[pct],
                orientation='h',
                marker=dict(
                    color=colors.get(mode, "#999"),
                    line=dict(color='black', width=1)
                ),
                name=str(mode),
                hovertemplate=f"{mode}: {pct:.1%}<extra></extra>",
                legendgroup=legend_group,
                legendgrouptitle_text=legend_group_title,
                text=[f"{pct:.1%}"],
                textposition="inside",
                insidetextanchor="middle",
                insidetextfont=dict(family='Times', size=20, color='black')
            )
        )
    return traces

In [493]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

# Column bar plots print raw values, rather than percentages
def make_single_column_panel(modes, percents, colors, panel_label, legend_group, legend_group_title):
    traces = []
    for mode, pct in zip(modes, percents):
        traces.append(
            go.Bar(
                x=[panel_label],         # one column per panel
                y=[pct],                 # height = percent
                orientation='v',
                marker=dict(
                    color=colors.get(mode, "#999"),
                    line=dict(color='black', width=1)
                ),
                name=str(mode),
                hovertemplate=f"{mode}: {round(pct)}<extra></extra>",
                legendgroup=legend_group,
                legendgrouptitle_text=legend_group_title,
                text=[round(pct)],
                textposition="inside",
                insidetextanchor="end",
                insidetextfont=dict(family='Times', size=20, color='black')
            )
        )
    return traces

In [494]:
def prepare_counts(df, mode_col, distance_col, threshold=0.02):
    counts = (
        df.groupby(mode_col)
          .agg({distance_col: "count"})
          .rename(columns={distance_col: "count"})
          .sort_values("count", ascending=False)
    )

    total = counts["count"].sum()

    if total == 0:
        return ["Other"], [1.0], [0]

    large_categories = {}
    other_count = 0

    for mode, count in counts["count"].items():
        proportion = count / total

        if proportion < threshold:
            other_count += count
        else:
            large_categories[mode] = count

    if other_count > 0:
        large_categories["Other"] = other_count

    modes = list(large_categories.keys())
    trip_counts = list(large_categories.values())
    percents = [c / total for c in trip_counts]

    return modes, percents, trip_counts


# Used to count distance in miles
def prepare_sums(df, group_col, distance_col, threshold=0.02):

    df_u80 = df

    # Group & count
    counts_by_group = (
        df_u80.groupby(group_col)[distance_col]
              .sum()
              .sort_values(ascending=False)
    )

    total = counts_by_group.sum()

    if total == 0:
        return ["Other"], [1.0], [0]

    large_categories = {}
    other_count = 0

    for mode, count in counts_by_group.items():
        proportion = count / total

        if proportion < threshold:
            other_count += count
        else:
            large_categories[mode] = count

    if other_count > 0:
        large_categories["Other"] = other_count

    modes = list(large_categories.keys())
    counts = list(large_categories.values())
    percents = [c / total for c in counts]

    return modes, percents, counts

In [495]:
def filter_u80(df, distance_col, reference_df):
    """Filter to trips at or below the 80th percentile distance."""
    cutoff = reference_df[distance_col].quantile(0.8)

    if pd.isna(cutoff):
        cutoff = 0

    return df[df[distance_col] <= cutoff]

In [496]:
def build_trip_plot(
    distance_col,
    panels,
    plot_title="",
    file_name="",
    threshold=0.00,
    apply_u80=False,
    layout=None,
    num_legends=1,
    use_distance=False,
    orientation="h",
    use_raw_values=False
):
    """
    Build a stacked multi-panel trip mode plot.
    `panels` must be a list of dictionaries. Each dict represents one panel.

    Required keys per panel:
        df          -> dataframe
        text        -> quality text description
        label       -> label for this panel ("User Labeled", "Inferred", etc.)
        legend_title-> legend group title
        mode_col    -> column for mode classification
        colors      -> color mapping for that panel
    """

    if not isinstance(panels, list) or len(panels) == 0:
        raise ValueError("`panels` must be a non-empty list of panel specifications.")

    required_keys = {"df", "text", "label", "legend_title", "mode_col", "colors"}
    for i, p in enumerate(panels):
        missing = required_keys - p.keys()
        if missing:
            raise ValueError(f"Panel {i+1} is missing required keys: {missing}")

    # Build subplot titles
    # subplot_titles = [
    #     f"{p['label']}<br>{p['text']}" for p in panels
    # ]

    subplot_titles = [
        f"{p.get('title', p['label'])}<br>{p['text']}" for p in panels
    ]

    fig = make_subplots(
        rows=len(panels),
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.1,
        subplot_titles=subplot_titles,
    )

    # Add each panel's traces
    for i, p in enumerate(panels, start=1):

        # Data processing steps
        if use_raw_values:
            # modes = p["df"][p["mode_col"]]
            # percents = p["df"][distance_col]
            modes = p["df"][p["mode_col"]].tolist()
            percents = p["df"][distance_col].tolist()
            counts = p["df"]["Count"].tolist() if "Count" in p["df"].columns else [None]*len(modes)
            
        elif use_distance:
            modes, percents, counts = prepare_counts(
                p["df"], p["mode_col"], distance_col, threshold
            )
        else:
            modes, percents, counts = prepare_sums(
                p["df"], p["mode_col"], distance_col, threshold
            )

        # Vertical or horizontal bar plots
        if orientation == "h":
            traces = make_single_row_panel(
                modes,
                percents,
                p["colors"],
                p["label"],
                legend_group=f"group_{p['label'].lower().replace(' ', '_')}",
                legend_group_title=p["legend_title"],
            )
        else:
            traces = make_single_column_panel(
                modes,
                percents,
                p["colors"],
                p["label"],
                legend_group=f"group_{p['label'].lower().replace(' ', '_')}",
                legend_group_title=p["legend_title"],
            )


        showlegend = p.get("show_legend", True)

        for t in traces:
            t.showlegend = showlegend
            fig.add_trace(t, row=i, col=1)


    # default laout applied if none provided
    if layout is None:
        layout = dict(
            height=350 * len(panels),
            barmode="stack",
            showlegend=True,
            legend=dict(
                orientation="v",
                yanchor="top",
                xanchor="left",
                valign="top",
                traceorder="grouped",
                itemsizing="constant",
            ),
            title=dict(text="PLOT TITLE", x=0.0),
        )
    else:
        fig.update_layout(layout)


    fig.update_xaxes(tickformat=".0%")
    output_name = f"{file_name}.html"
    fig.write_html(output_name, include_plotlyjs="cdn", full_html=True)

    return fig, output_name

In [497]:
### Number of trips for each mode

In [498]:
text_results = [["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"]]

panels = [
    {
        "df": expanded_ct,
        "text": stacked_bar_quality_text_labeled,
        "label": "Labeled by User",
        "legend_title": "User-Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": True
    },

    {
        "df": expanded_ct_inferred,
        "text": stacked_bar_quality_text_inferred,
        "label": "Inferred from prior labels",
        "legend_title": "Inferred Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": False
    },

    {
        "df": expanded_ct_sensed,
        "text": stacked_bar_quality_text_sensed,
        "label": "Sensed from prior labels",
        "legend_title": "Sensed Modes",
        "mode_col": "primary_mode",
        "colors": colors_sensed,
        "show_legend": True
    }
]

#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_title = "Number of trips for each mode"
plot_one_layout = dict(height=900,barmode='stack',showlegend=True,title=dict(text=plot_title, x=0.5),legend=dict(orientation="v",traceorder="grouped",tracegroupgap=10))

fig, filename = build_trip_plot(
    distance_col="distance",
    plot_title="Number of trips for each mode",
    file_name="Number_trips_each_mode",
    panels=panels,
    threshold=0.02,
    layout=plot_one_layout,
    use_distance=True
)

fig.update_layout(plot_one_layout)

In [499]:
trip_purpose_query = "purpose_confirm == 'work'"

expanded_ct_commute = expanded_ct.query(trip_purpose_query)
commute_quality_text = scaffolding.get_quality_text(expanded_ct, expanded_ct_commute, "commute", include_test_users) if not expanded_ct.empty else ""
expanded_ct_inferred_commute = expanded_ct_inferred.query(trip_purpose_query)
commute_quality_text_inferred = scaffolding.get_quality_text(expanded_ct_inferred, expanded_ct_inferred_commute, "commute", include_test_users) if not expanded_ct_inferred.empty else ""

commute_labeled_match = re.match(r'Based on ([0-9]+) confirmed commute trips from ([0-9]+) (users|testers and participants)\nof ([0-9]+) total confirmed trips from ([0-9]+) (users|testers and participants) (\(([0-9.]+|nan)%\))', commute_quality_text)
stacked_bar_quality_text_commute_labeled = f"{commute_labeled_match.group(1)} trips {commute_labeled_match.group(7)}\n from {commute_labeled_match.group(2)} {commute_labeled_match.group(3)}"

commute_inferred_match = re.match(r'Based on ([0-9]+) confirmed commute trips from ([0-9]+) (users|testers and participants)\nof ([0-9]+) total confirmed trips from ([0-9]+) (users|testers and participants) (\(([0-9.]+|nan)%\))', commute_quality_text_inferred)
stacked_bar_quality_text_commute_inferred = f"{commute_inferred_match.group(1)} trips {commute_inferred_match.group(7)}\n from {commute_inferred_match.group(2)} {commute_inferred_match.group(3)}"

panels = [
    {
        "df": expanded_ct_commute,
        "text": stacked_bar_quality_text_commute_labeled,
        "label": "Labeled by User",
        "legend_title": "User Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode
    },
    {
        "df": expanded_ct_inferred_commute,
        "text": stacked_bar_quality_text_commute_inferred,
        "label": "Inferred from prior labels",
        "legend_title": "Model Inferred Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode
    }
]

plot_title = "Number of commute trips for each mode"
plot_two_layout=dict(
    height=350 * len(panels),
    barmode="stack",
    showlegend=True,
    legend=dict(
        orientation="v",
        yanchor="top",
        xanchor="left",
        valign="top",
        traceorder="grouped",
        itemsizing="constant",),
    title=dict(text=plot_title, x=0.5)
    )

fig, filename = build_trip_plot(
    distance_col="distance",
    plot_title="Number of commute trips for each mode",
    file_name="Commute_trips_each_mode",
    panels=panels,
    threshold=0.02,
    layout=plot_two_layout,
    use_distance=True
)

fig.update_layout(plot_two_layout)

Based on 356 confirmed commute trips from 17 users
of 5279 total confirmed trips from 25 users (6.74%)
Based on 462 confirmed commute trips from 17 users
of 6669 total confirmed trips from 25 users (6.93%)

In [500]:
### Number of trips for each purpose

In [501]:
plot_title_no_quality="Number of trips for each purpose"
file_name= f"ntrips_purpose{file_suffix}"
text_results = [["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"]]

# Used for plots that don't have assigned colors
PURPOSE_COLORS = {
"work": "pink",
"school": "lightsteelblue",
"shopping": "palegreen",
"social": "khaki",
"other": "plum",
"home": "lightblue",
"entertainment": "peachpuff",
"meal": "mistyrose",
"access_recreation": "lightyellow",
"personal_med": "palegoldenrod",
"pick_drop_person": "thistle",
"transit_transfer": "lightcyan",
"at_work": "honeydew",
"relig": "lavenderblush"
}

panels = [
    {
        "df": expanded_ct,
        "text": stacked_bar_quality_text_labeled,
        "label": "Labeled by User",
        "legend_title": "User Labeled Modes",
        "mode_col": "purpose_confirm_w_other",
        "colors": PURPOSE_COLORS
    },

    {
        "df": expanded_ct_inferred,
        "text": stacked_bar_quality_text_inferred,
        "label": "Inferred from prior labels",
        "legend_title": "Model Inferred Modes",
        "mode_col": "purpose_confirm_w_other",
        "colors": PURPOSE_COLORS
    }

]


# ['stack', 'group', 'overlay', 'relative']
# ADD GROUP STACK TOGGLE ACCOMODATE GENERIC FUNCTIONS - could toggling mode be interactive
plot_title_no_quality="Number of trips for each purpose"


# CREATE LAYOUT INSIDE BUILD TRIP LAYOUT, MANY REPEATED STYLING CHOICES
# PASS IN BAR MODE - 
plot_three_layout=dict(
    height=900,
    barmode='stack',
    showlegend=True,
    title=dict(text="Number of trips for each purpose", x=0.5),
    legend=dict(
        orientation="v",
        traceorder="grouped",
        tracegroupgap=10
    ),

)

fig, filename = build_trip_plot(
    distance_col="distance",
    plot_title=plot_title_no_quality,
    file_name="ntrips_purpose",
    panels=panels,
    threshold=0.02,
    layout=plot_three_layout,
    use_distance=True
)

fig.update_layout(plot_three_layout)

In [502]:
# Mode choice for trips under 80% mark - under 9.7 miles splish!!

In [503]:

cutoff = expanded_ct_sensed.distance.quantile(0.8)
dist_threshold = expanded_ct_sensed[distance_col].quantile(0.8).round(1)
dist_threshold = str(dist_threshold) 

plot_title_no_quality="Number of trips per travel model under " + dist_threshold + " " + label_units_lower
plot_title_no_quality=plot_title_no_quality+"\n["+dist_threshold + " " + label_units_lower+" represents 80th percentile of trip length]"

## We do an existence check for the labeled df because we want to display the sensed value even if we don't have the labeled value
## but we don't need to have an existence check for sensed because in that case we will have no data to display
expanded_ct_u80 = expanded_ct.loc[(expanded_ct['distance'] <= cutoff)] if "mode_confirm_w_other" in expanded_ct.columns else None
expanded_ct_inferred_u80 = expanded_ct_inferred.loc[(expanded_ct_inferred['distance'] <= cutoff)] if "mode_confirm_w_other" in expanded_ct_inferred.columns else None
expanded_ct_sensed_u80 = expanded_ct_sensed.loc[(expanded_ct_sensed['distance'] <= cutoff)]

sensed_u80_quality_text = f"{len(expanded_ct_sensed_u80)} trips ({round(len(expanded_ct_sensed_u80)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(expanded_ct_sensed_u80)} {sensed_match.group(3)}"
labeled_u80_quality_text = f"{len(expanded_ct_u80)} trips ({round(len(expanded_ct_u80)/len(expanded_ct)*100)}% of all labeled,\n{round(len(expanded_ct_u80)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(expanded_ct_u80)} {sensed_match.group(3)}" if "mode_confirm_w_other" in expanded_ct.columns else "0 labeled trips"
inferred_u80_quality_text = f"{len(expanded_ct_inferred_u80)} trips ({round(len(expanded_ct_inferred_u80)/len(expanded_ct_inferred)*100)}% of all inferred,\n{round(len(expanded_ct_inferred_u80)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(expanded_ct_inferred_u80)} {sensed_match.group(3)}" if "mode_confirm_w_other" in expanded_ct_inferred.columns else "0 inferred trips"

In [504]:
panels = [
    {
        "df": expanded_ct_u80,
        "text": labeled_u80_quality_text,
        "label": "Labeled by User",
        "legend_title": "User-Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": True,
    },

    {
        "df": expanded_ct_inferred_u80,
        "text": inferred_u80_quality_text,
        "label": "Inferred from prior labels",
        "legend_title": "Inferred Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": False,
    },

    {
        "df": expanded_ct_sensed_u80,
        "text": sensed_u80_quality_text,
        "label": "Sensed from prior labels",
        "legend_title": "Sensed Modes",
        "mode_col": "primary_mode",
        "colors": colors_sensed,
        "show_legend": True,
    }
]

plot_four_layout = dict(   
    height=600,
    barmode='stack',
    showlegend=True,
    title=dict(text="Number of trips per travel model under 9.7 miles", x=0.5),
    legend=dict(
        orientation="v",
        traceorder="grouped",
        tracegroupgap=10
    )
)



plot_title = "Mode choice for trips under 80% mark - under 9.7 miles"
filename = f"Mode_choice_under_80{file_suffix}"

fig, filename = build_trip_plot(
    distance_col="distance",
    panels=panels,
    plot_title=plot_title,
    file_name=filename,
    threshold=0.02,
    apply_u80=True,
    layout=plot_four_layout,
    num_legends=1,
    use_distance=True
)

fig.update_layout(plot_four_layout)

In [505]:
# Miles for each mode

In [506]:
plot_five_layout = dict(   
    height=600,
    barmode='stack',
    showlegend=True,
    title=dict(text="Miles for each mode", x=0.5),
    legend=dict(
        orientation="v",
        traceorder="grouped",
        tracegroupgap=10
    )
)

In [507]:
text_results = [["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"]]

panels = [
    {
        "df": expanded_ct,
        "text": stacked_bar_quality_text_labeled,
        "label": "Labeled by User",
        "legend_title": "User-Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": True
    },

    {
        "df": expanded_ct_inferred,
        "text": stacked_bar_quality_text_inferred,
        "label": "Inferred from prior labels",
        "legend_title": "Inferred Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": False
    },

    {
        "df": expanded_ct_sensed,
        "text": stacked_bar_quality_text_sensed,
        "label": "Sensed from prior labels",
        "legend_title": "Sensed Modes",
        "mode_col": "primary_mode",
        "colors": colors_sensed,
        "show_legend": True
    }
]

#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_title = "Miles Traveled for each mode"
plot_five_layout = dict(height=900,barmode='stack',showlegend=True,title=dict(text=plot_title, x=0.49),legend=dict(orientation="v",traceorder="grouped",tracegroupgap=10))

fig, filename = build_trip_plot(
    distance_col="distance",
    plot_title="plot_title",
    file_name="Miles_each_mode",
    panels=panels,
    threshold=0.02,
    layout=plot_five_layout,
    use_distance=False
)

fig.update_layout(plot_five_layout)

In [508]:
#Total Trip Length covered by each land transport mode

In [509]:
plot_six_layout = dict(   
    height=600,
    barmode='stack',
    showlegend=True,
    title=dict(text="Miles for each mode", x=0.5),
    legend=dict(
        orientation="v",
        traceorder="grouped",
        tracegroupgap=10
    )
)

In [510]:
labeled_land_trips_df = expanded_ct[expanded_ct['base_mode'] != "AIR"] if "base_mode" in expanded_ct.columns else None
inferred_land_trips_df = expanded_ct_inferred[expanded_ct_inferred['base_mode'] != "AIR"] if "base_mode" in expanded_ct_inferred.columns else None
sensed_land_trips_df = expanded_ct_sensed[expanded_ct_sensed['primary_mode'] != "AIR_OR_HSR"]

labeled_land_quality_text = f"{len(labeled_land_trips_df)} trips ({round(len(labeled_land_trips_df)/len(expanded_ct)*100)}% of all labeled,\n{round(len(labeled_land_trips_df)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(labeled_land_trips_df)} {sensed_match.group(3)}" if "mode_confirm_w_other" in expanded_ct.columns else "0 labeled trips"
inferred_land_quality_text = f"{len(inferred_land_trips_df)} trips ({round(len(inferred_land_trips_df)/len(expanded_ct_inferred)*100)}% of all inferred,\n{round(len(inferred_land_trips_df)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(inferred_land_trips_df)} {sensed_match.group(3)}" if "mode_confirm_w_other" in expanded_ct_inferred.columns else "0 inferred trips"
sensed_land_quality_text = f"{len(sensed_land_trips_df)} trips ({round(len(sensed_land_trips_df)/len(expanded_ct_sensed)*100)}% of all trips)\nfrom {scaffolding.unique_users(sensed_land_trips_df)} {sensed_match.group(3)}"

In [511]:
text_results = [["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"], ["Unmodified Alt Text", "Unmodified HTML"]]

panels = [
    {
        "df": labeled_land_trips_df,
        "text": labeled_land_quality_text,
        "label": "Labeled by User",
        "legend_title": "User-Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": True
    },

    {
        "df": inferred_land_trips_df,
        "text": inferred_land_quality_text,
        "label": "Inferred from prior labels",
        "legend_title": "Inferred Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": False
    },

    {
        "df": sensed_land_trips_df,
        "text": sensed_land_quality_text,
        "label": "Sensed from prior labels",
        "legend_title": "Sensed Modes",
        "mode_col": "primary_mode",
        "colors": colors_sensed,
        "show_legend": True
    }
]

#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_title = "Total trip length (" + label_units_lower + ") covered by each mode on land"
plot_six_layout = dict(height=900,barmode='stack',showlegend=True,title=dict(text=plot_title, x=0.49),legend=dict(orientation="v",traceorder="grouped",tracegroupgap=10))


fig, filename = build_trip_plot(
    distance_col="distance",
    plot_title="plot_title",
    file_name="Total_trip_length_miles_each_mode",
    panels=panels,
    threshold=0.02,
    layout=plot_six_layout,
    use_distance=False
)

fig.update_layout(plot_six_layout)

In [512]:
# Average miles per transport mode selected (Mode_confirm)

In [513]:
plot_title_no_quality="Average "+ label_units+" for each mode with > 3 entries"
file_name ='average_miles_mode_confirm%s' % file_suffix

dist = expanded_ct.groupby('mode_confirm_w_other').agg({distance_col: ['sum', 'count' , 'mean']})
dist.columns = ['Total ('+label_units_lower+')', 'Count', 'Average ('+label_units_lower+')']
dist = dist.reset_index()
dist =dist.sort_values(by=['Total ('+label_units_lower+')'], ascending=False)

x='mode_confirm_w_other'
y='Average ('+label_units_lower+')'
x_label= "Confirmed Mode of Transportation"
plot_title= plot_title_no_quality+"\n"+quality_text

print(dist.columns)

data = dist.drop((dist.query("Count < 3").index)).sort_values(by=['Average ('+label_units_lower+')'], ascending=False)

Index(['mode_confirm_w_other', 'Total (miles)', 'Count', 'Average (miles)'], dtype='object')

In [514]:
panels = [
    {
        "df": data,
        "text": "",
        "label": "",
        "legend_title": "User-Labeled Modes",
        "mode_col": "mode_confirm_w_other",
        "colors": colors_mode,
        "show_legend": True
    }
]

In [519]:
#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_seven_layout = dict(
    height=900,
    barmode='group',
    showlegend=True,
    title=dict(text=plot_title, x=0.47),
    legend=dict(orientation="v",traceorder="reversed",tracegroupgap=10),
    yaxis=dict(
        title="Average (" + label_units + ")",
        tickformat=",.0f"
    ),
    xaxis=dict(
        title=x_label
    )
)


fig, filename = build_trip_plot(
    distance_col="Average ("+label_units_lower+")",
    plot_title=plot_title,
    file_name="Total_trip_length_miles_each_mode",
    panels=panels,
    threshold=0.00,
    layout=plot_seven_layout,
    use_distance=False,
    orientation="v",
    use_raw_values=True
)

fig.update_layout(plot_seven_layout)

In [516]:
# Number of trips by day¶

In [594]:
plot_title_no_quality="Number of trips by day"
file_name ='ntrips_per_day%s' % file_suffix

In [595]:
plot_title_no_quality="Number of trips by day"
file_name ='ntrips_per_day%s' % file_suffix

try:
    fq_days = expanded_ct.groupby(['start_local_dt_day']).agg({'start_local_dt_day': ['sum', 'count']})
    fq_days = fq_days.reset_index()
    fq_days.columns = ['Day of the Month', 'Total', 'Number of Trips']

    data = fq_days
    x = 'Day of the Month'
    y = 'Number of Trips'
    
    plot_title= plot_title_no_quality+"\n"+quality_text

    # barplot_day(data,x,y,plot_title,file_name)
    alt_text = store_alt_text_bar(pd.DataFrame(data['Number of Trips'].values, data['Day of the Month']), file_name, plot_title)
except:
    generate_missing_plot(plot_title_no_quality,debug_df,file_name)
    alt_text = store_alt_text_missing(debug_df, file_name, plot_title_no_quality)

In [596]:
panels = [
    {
        "df": data,
        "text": "",
        "label": "",
        "legend_title": "",
        "mode_col": "Day of the Month",
        "colors": {"DEFAULT": "blue"},   # only one entry
        "show_legend": False
    }
]

In [598]:
#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_eight_layout = dict(
    height=900,
    barmode='group',
    showlegend=True,
    title=dict(text=plot_title, x=0.47),
    legend=dict(orientation="v",traceorder="reversed",tracegroupgap=10),
    yaxis=dict(
        title="Number of Trips"),
    xaxis=dict(
        title="Day of the Month"),

    bargroupgap=0.3,

)


fig, filename = build_trip_plot(
    distance_col="Number of Trips",
    plot_title=plot_title,
    file_name="Number_of_trips",
    panels=panels,
    threshold=0.00,
    layout=plot_eight_layout,
    use_distance=False,
    orientation="v",
    use_raw_values=True
)

fig.update_traces(marker=dict(color="blue"))
fig.update_traces(insidetextfont=dict(color="white"))
fig.update_layout(plot_eight_layout)

In [582]:
#Number of trips by day of week

In [599]:
plot_title_no_quality="Number of trips by weekday"
file_name ='ntrips_per_weekday%s' % file_suffix
try:
    fq_weekdays = expanded_ct.groupby(['start_local_dt_weekday']).agg({'start_local_dt_weekday': ['sum', 'count']})
    fq_weekdays = fq_weekdays.reset_index()
    fq_weekdays.columns = ['Weekday', 'Total', 'Number of Trips']
    weekday_labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    fq_weekdays["Weekday"] = fq_weekdays.Weekday.apply(lambda x: weekday_labels[x])

    data = fq_weekdays
    x = 'Weekday'
    y = 'Number of Trips'

    plot_title= plot_title_no_quality+"\n"+quality_text
    
    alt_text = store_alt_text_bar(pd.DataFrame(data['Number of Trips'].values, data['Weekday']), file_name, plot_title)
except:
    alt_text = store_alt_text_missing(debug_df, file_name, plot_title_no_quality)

In [602]:
panels = [
    {
        "df": data,
        "text": "",
        "label": "",
        "legend_title": "",
        "mode_col": "Weekday",
        "colors": {"DEFAULT": "blue"},   # only one entry
        "show_legend": False
    }
]

In [605]:
#layout + column params - TITLE IS DEFINED IN LAYOUT below, NOT IN BUILD_TRIP_PLOT
plot_nine_layout = dict(
    height=900,
    barmode='group',
    showlegend=True,
    title=dict(text=plot_title, x=0.47),
    legend=dict(orientation="v",traceorder="reversed",tracegroupgap=10),
    yaxis=dict(
        title="Number of Trips"),
    xaxis=dict(
        title="Day of the Week"),
    bargroupgap=0.2,

)


fig, filename = build_trip_plot(
    distance_col="Number of Trips",
    plot_title=plot_title,
    file_name="Number_of_trips",
    panels=panels,
    threshold=0.00,
    layout=plot_nine_layout,
    use_distance=False,
    orientation="v",
    use_raw_values=True
)

fig.update_traces(marker=dict(color="blue"))
fig.update_traces(insidetextfont=dict(color="white"))
fig.update_layout(plot_nine_layout)